## TODO: テンプレートに色々記載する

AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AZ1Parameter:
    Type: String
    Default: "ap-northeast-1a"
    Description: "select availability zone"
  
  AZ2Parameter:
    Type: String
    Default: "ap-northeast-1c"
    Description: "select availability zone"
  
  ProjectNameParameter:
    Type: String
    Default: "Sample"
    Description: "Project name for tag"

LogicalID:
  Type: "AWS::EC2::Instance"
  Properties:
    AdditionalInfo: String
    Affinity: String
    AvailabilityZone: String
    BlockDeviceMappings:
      - BlockDeviceMapping
    CpuOptions:
      CpuOptions
    CreditSpecification:
      CreditSpecification
    DisableApiTermination: Boolean
    EbsOptimized: Boolean
    ElasticGpuSpecifications:
      - ElasticGpuSpecification
    ElasticInferenceAccelerators:
      - ElasticInferenceAccelerator
    HostId: String
    IamInstanceProfile: String
    ImageId: String
    InstanceInitiatedShutdownBehavior: String
    InstanceType: String
    Ipv6AddressCount: Integer
    Ipv6Addresses:
      - InstanceIpv6Address
    KernelId: String
    KeyName: String
    LaunchTemplate:
      LaunchTemplateSpecification
    LicenseSpecifications:
      - LicenseSpecification
    Monitoring: Boolean
    NetworkInterfaces:
      - NetworkInterface
    PlacementGroupName: String
    PrivateIpAddress: String
    RamdiskId: String
    SecurityGroupIds:
      - String
    SecurityGroups:
      - String
    SourceDestCheck: Boolean
    SsmAssociations:
      - SsmAssociation
    SubnetId: String
    Tags:
      - Tag
    Tenancy: String
    UserData: String
    Volumes:
      - Volume
