AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ProjectNameParameter:
    Type: String
    Default: 'Sample'
    Description: Project name for tag
  RDSInstanceTypeParameter:
    Type: String
    Default: 'db.t2.micro'  ## 12ヶ月無料枠
    Description: rds instance type
  RDSUserParameter:
    Type: String
    Default: 'admin'
    Description: rds root user
  RDSPasswordParameter:
    Type: String
    Default: ''
    Description: rds root password

Resources:
  RDSParameterGroup:
    Type: "AWS::Neptune::DBParameterGroup"
    Properties:
      Description: !Sub ${ProjectNameParameter} RDS Parameter Group
      Family: MySQL5.7
      Parameters:
        character_set_results: utf8mb4
        character_set_client: utf8mb4
        character_set_connection: utf8mb4

  RDSSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: !Sub ${ProjectNameParameter} RDS subnet group
      SubnetIds:
        - {"Fn::ImportValue": !Sub "${ProjectNameParameter}-PrivateSubnet1a"}
        - {"Fn::ImportValue": !Sub "${ProjectNameParameter}-PrivateSubnet1c"}
    Tags:
    - Key: Project
      Value:
        Ref: ProjectNameParameter

  # vpc.ymlで作成したものを使用する
  # RDSSecurityByEC2SecurityGroup:
  #   Type: "AWS::RDS::DBSecurityGroup"
  #   Properties:
  #     GroupDescription: "Ingress for Amazon EC2 security group"
  #     EC2VpcId: {"Fn::ImportValue": !Sub "${ProjectNameParameter}-VPC"}

  RDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBName:
        Ref: ProjectNameParameter
      DBInstanceIdentifier: !Sub ${AWS::StackName}-rds
      AutoMinorVersionUpgrade: false
      AllocatedStorage: "30"
      MultiAZ: false
      DBSubnetGroupName:
        Ref: RDSSubnetGroup
      DBParameterGroupName:
        Ref: RDSParameterGroup
      VPCSecurityGroups:
        - {"Fn::ImportValue": !Sub "${ProjectNameParameter}-Private-SG"}
      DBInstanceClass:
        Ref: RDSInstanceTypeParameter
      Engine: "MySQL"
      StorageType: "gp2"
      EngineVersion: "5.7"
      MasterUsername:
        Ref: "RDSUserParameter"
      MasterUserPassword:
        Ref: "RDSPasswordParameter"
      Tags:
      - Key: Project
        Value:
          Ref: ProjectNameParameter
